[package]
name = "libindy-crypto"
version = "0.1.0"
authors = ["Artemkaaas <artem.ivanov@dsr-company.com>"]

[lib]
name = "indy_crypto"
path = "src/lib.rs"
crate-type = ["staticlib","rlib", "dylib"]

[dependencies]
amcl = { version = "0.1.2", features = ["BLS383"]}
env_logger = "0.4.2"
lazy_static = "0.2"
libc = "0.2.21"
log = "0.3.7"
rand = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
sha1 = "0.2.0"