[package]
name = "libindy-crypto"
version = "0.1.0"
authors = ["Artemkaaas <artem.ivanov@dsr-company.com>"]

[lib]
name = "indy_crypto"
path = "src/lib.rs"
crate-type = ["staticlib","rlib", "dylib"]

[features]
default = ["pair_amcl"]
pair_amcl = ["amcl"]

[dependencies]
amcl = { version = "0.1.2",  optional = true, features = ["BLS383"]}
log = "0.3.7"
rand = "0.3"
sha1 = "0.2.0"